// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGhFLTq3t6p9qMjXB1c0agadqmfAdq7oc',
    appId: '1:847614059163:web:559464ee74e5429a421c3e',
    messagingSenderId: '847614059163',
    projectId: 'waxhub95',
    authDomain: 'waxhub95.firebaseapp.com',
    storageBucket: 'waxhub95.firebasestorage.app',
    measurementId: 'G-GFZSE4W710',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI9YZ1ZDqVkPKG8mH6CLAlslhsNX_fnQY',
    appId: '1:847614059163:android:b28aea67877c3a5c421c3e',
    messagingSenderId: '847614059163',
    projectId: 'waxhub95',
    storageBucket: 'waxhub95.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGhFLTq3t6p9qMjXB1c0agadqmfAdq7oc',
    appId: '1:847614059163:web:58d5938476cbb1b8421c3e',
    messagingSenderId: '847614059163',
    projectId: 'waxhub95',
    authDomain: 'waxhub95.firebaseapp.com',
    storageBucket: 'waxhub95.firebasestorage.app',
    measurementId: 'G-J67W6C83Y4',
  );
}